Remove 'ssh_gauthenticator_script_check' & Update PAM script.

diff --git a/roles/ssh_gauthenticator/defaults/main.yml b/roles/ssh_gauthenticator/defaults/main.yml
--- a/roles/ssh_gauthenticator/defaults/main.yml
+++ b/roles/ssh_gauthenticator/defaults/main.yml
@@ -1,32 +1,27 @@
 ---
-# google-authenticator check script for pam_exec
-ssh_gauthenticator_script_check: |
+ssh_gauthenticator_pam_script: |
   #!/bin/bash
-  # this script, called by pam_exec in pam.d/ssh,
-  # change the shell to run google authenticator
-  # if $HOME/.google_authenticator is missing
-  # otherwise set shell to /bin/bash
+  # PAM script to setup google authenticator
   trap 'exit 1' SIGINT
-  homedir=`getent passwd "$PAM_USER" | cut -d: -f6`
-  usershell=`getent passwd "$PAM_USER" | cut -d: -f7`
-  if [ ! -f $homedir/.google_authenticator ] && [ "$usershell" != "/usr/local/bin/garun.sh" ]; then
-    chsh -s /usr/local/bin/garun.sh $PAM_USER
-    echo -e "\n\n Multi-factor authentication is not configured. Please log in again to configure it."
-    echo -e " -----------------------------------------------------------------------------------\n\n"
+  if [ "$PAM_TYPE" != "open_session" ]; then
+    exit 0
+  fi
+  USER=$PAM_USER
+  if [ -z "$USER" ]; then
+    echo "PAM_USER not set, exiting."
     exit 1
-  elif [ "$usershell" == "/usr/local/bin/garun.sh" ]; then
-    chsh -s /bin/bash $PAM_USER
   fi
-
-# temporary shell script to run google-authenticator configuration
-ssh_gauthenticator_script_run: |
-  #!/bin/bash
-  # this script run google authenticator
-  # when $HOME/.google_authenticator is missing
-  trap 'exit 1' SIGINT
-  if [ ! -f $HOME/.google_authenticator ]; then
-    /usr/bin/google-authenticator -t -D -f -r 3 -R 30 -w 2
+  HOME=$(eval echo ~$USER)
+  if [ ! -d "$HOME" ]; then
+    echo "Can't access HOME directory, exiting."
+    exit 1
   fi
+  if [ -f "$HOME/.google_authenticator" ]; then
+    exit 0
+  fi
+  su - "$USER" -c "/usr/bin/google-authenticator -C -t -D -f -Q ANSI -r 3 -R 30 -w 2"
+  # force logout
+  exit 1
 
 # configuration for sshd_config
 ssh_gauthenticator_sshd_config:
@@ -56,11 +51,11 @@ ssh_gauthenticator_pam_ssh_path: /etc/pam.d/sshd
 ssh_gauthenticator_pam_ssh_bif: |
   # two-factor authentication via google authenticator.
   # nullok & pam_permit allow users to log in without an
-  # OTP (if not already configured) and gachk.sh checks
-  # and forces google authenticator configuration.
-  auth     required   pam_google_authenticator.so nullok
-  auth     required   pam_permit.so
-  session  required   pam_exec.so stdout seteuid /usr/local/bin/gachk.sh
+  # OTP (if not already configured) and garun.sh checks
+  # and run google authenticator configuration.
+  auth required pam_google_authenticator.so nullok
+  auth required pam_permit.so
+  session required pam_exec.so stdout seteuid /usr/local/bin/gapam.sh
 
 # blockinfile insertafter
 ssh_gauthenticator_pam_ssh_bif_after: "^.*@include common-auth"
